// Generated by CoffeeScript 1.6.3
steroids.config.name = "ListaMobile";

steroids.config.location = "index.html";

steroids.config.navigationBar.tintColor = "#00aeef";

steroids.config.navigationBar.titleColor = "#ffffff";

steroids.config.navigationBar.buttonTintColor = "#000000";

steroids.config.navigationBar.buttonTitleColor = "#ffffff";

steroids.config.loadingScreen.tintColor = "#262626";

steroids.config.statusBar.enabled = true;

steroids.config.statusBar.style = "default";
