// Generated by CoffeeScript 1.6.3
var Collection, Todo, Todos, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Collection = require('./collection');

Todo = require('models/todo');

module.exports = Todos = (function(_super) {
  __extends(Todos, _super);

  function Todos() {
    _ref = Todos.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  Todos.prototype.model = Todo;

  Todos.prototype.initialize = function() {
    return this.localStorage = new Store('todos');
  };

  Todos.prototype.done = function() {
    return this.filter(function(todo) {
      return todo.get('done');
    });
  };

  Todos.prototype.remaining = function() {
    return this.without.apply(this, this.done());
  };

  Todos.prototype.nextOrder = function() {
    if (!this.length) {
      return 1;
    }
    return this.last().get('order') + 1;
  };

  Todos.prototype.comparator = function(todo) {
    return todo.get('order');
  };

  Todos.prototype.clearCompleted = function() {
    return _.each(this.done(), function(todo) {
      return todo.clear();
    });
  };

  return Todos;

})(Collection);
